"for_loop:\n\t"
"addi %[others_cnt], %[others_cnt], 1\n\t"

"lw t0, 0(%[h])\n\t"
"lw t1, 0(%[x])\n\t"
"addi %[lw_cnt], %[lw_cnt], 2\n\t"

"mul t1, t1, t0\n\t"
"addi %[mul_cnt], %[mul_cnt], 1\n\t"
"add t1, t1, %[id]\n\t"
"addi %[add_cnt], %[add_cnt], 1\n\t"
"sh t1, 0(%[y])\n\t"
"addi %[sw_cnt], %[sw_cnt], 1\n\t"

"addi %[y], %[y], 2\n\t"
"addi %[h], %[h], 2\n\t"
"addi %[x], %[x], 2\n\t"
"addi %[arr_size], %[arr_size], -1\n\t"
"addi %[add_cnt], %[add_cnt], 4\n\t"
"bnez %[arr_size], for_loop\n\t"
"exit:\n\t"
